### ISSUE TITLE
Latin accents

### ISSUE THREAD

**Issue by heraldo1980** [JoshuaMKW/SMS-Message-Editor#2]
I remembered that your tool does not support some accents in my language, such as 'í' 'ç' 'ã' and others, I would really like it if you could add this to your wonderful tool.

**Comment by JoshuaMKW** [comment]
Hello! You must understand- the tool doesn't support Latin characters because the game doesn't support such characters. Even when you select translations when playing the PAL build of the game, it is just SHIFT-JIS characters that map to the glyphs of the specific language. This is different from how modern systems using UTF handle different languages and thus I can't support it in the way you want. Thanks for the concern though.
